package com.vermeg.ala17.document;

import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class QuestionDocument {
    private Long author_id;
    private Date created_at;
    private Long up_votes;
    private String title;
    private Long down_votes;
    private boolean is_solved;
    private Long id;
    private Date updated_at;
    private String txt;
    private List<LilTagDoc> tags;
    //generated by logstash
    //private String type;
}
